package com.hk.deader.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Avtomat generated by hbm2java
 */
@Entity
@Table(name = "AVTOMAT")
public class Avtomat implements java.io.Serializable {

	private static final long serialVersionUID = 345521404066623266L;
	private int num;
	private String operator;
	private float cena;
	private Double cenabut;
	private Double rezerv;
	private Double voda;
	private String tel;
	private String adr;
	private String prim;
	private Date trevdat;
	private Date vodadat;
	private Date pitdat;
	private Date novodadat;
	private Date temdat;
	private String stat;
	private String rezh;
	private short flag;
	private Integer po;
	private Date rezdat;
	private Date zasordat;
	private Date dat;

	public Avtomat() {
	}

	public Avtomat(int num, String rezh, short flag) {
		this.num = num;
		this.rezh = rezh;
		this.flag = flag;
	}

	public Avtomat(int num, String operator, float cena, Double cenabut,
			Double rezerv, Double voda, String tel, String adr, String prim,
			Date trevdat, Date vodadat, Date pitdat, Date novodadat,
			Date temdat, String stat, String rezh, short flag, Integer po,
			Date rezdat, Date zasordat, Date dat) {
		this.num = num;
		this.operator = operator;
		this.cena = cena;
		this.cenabut = cenabut;
		this.rezerv = rezerv;
		this.voda = voda;
		this.tel = tel;
		this.adr = adr;
		this.prim = prim;
		this.trevdat = trevdat;
		this.vodadat = vodadat;
		this.pitdat = pitdat;
		this.novodadat = novodadat;
		this.temdat = temdat;
		this.stat = stat;
		this.rezh = rezh;
		this.flag = flag;
		this.po = po;
		this.rezdat = rezdat;
		this.zasordat = zasordat;
		this.dat = dat;
	}

	@Id
	@Column(name = "NUM", unique = true, nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Column(name = "OPERATOR", length = 32)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "CENA", precision = 15, scale = 0)
	public float getCena() {
		return this.cena;
	}

	public void setCena(float cena) {
		this.cena = cena;
	}

	@Column(name = "CENABUT", precision = 15, scale = 0)
	public Double getCenabut() {
		return this.cenabut;
	}

	public void setCenabut(Double cenabut) {
		this.cenabut = cenabut;
	}

	@Column(name = "REZERV", precision = 15, scale = 0)
	public Double getRezerv() {
		return this.rezerv;
	}

	public void setRezerv(Double rezerv) {
		this.rezerv = rezerv;
	}

	@Column(name = "VODA", precision = 15, scale = 0)
	public Double getVoda() {
		return this.voda;
	}

	public void setVoda(Double voda) {
		this.voda = voda;
	}

	@Column(name = "TEL", length = 24)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "ADR", length = 96)
	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	@Column(name = "PRIM")
	public String getPrim() {
		return this.prim;
	}

	public void setPrim(String prim) {
		this.prim = prim;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TREVDAT", length = 19)
	public Date getTrevdat() {		
		return this.trevdat;
	}

	public void setTrevdat(Date trevdat) {
		this.trevdat = trevdat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VODADAT", length = 19)
	public Date getVodadat() {
		return this.vodadat;
	}

	public void setVodadat(Date vodadat) {
		this.vodadat = vodadat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PITDAT", length = 19)
	public Date getPitdat() {
		return this.pitdat;
	}

	public void setPitdat(Date pitdat) {
		this.pitdat = pitdat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NOVODADAT", length = 19)
	public Date getNovodadat() {
		return this.novodadat;
	}

	public void setNovodadat(Date novodadat) {
		this.novodadat = novodadat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TEMDAT", length = 19)
	public Date getTemdat() {
		return this.temdat;
	}

	public void setTemdat(Date temdat) {
		this.temdat = temdat;
	}

	@Column(name = "STAT", length = 1)
	public String getStat() {
		return this.stat;
	}

	public void setStat(String stat) {
		this.stat = stat;
	}

	@Column(name = "REZH", nullable = false, length = 256)
	public String getRezh() {
		return this.rezh;
	}

	public void setRezh(String rezh) {
		this.rezh = rezh;
	}

	@Column(name = "FLAG", nullable = false)
	public short getFlag() {
		return this.flag;
	}

	public void setFlag(short flag) {
		this.flag = flag;
	}

	@Column(name = "PO")
	public Integer getPo() {
		return this.po;
	}

	public void setPo(Integer po) {
		this.po = po;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REZDAT", length = 19)
	public Date getRezdat() {
		return this.rezdat;
	}

	public void setRezdat(Date rezdat) {
		this.rezdat = rezdat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ZASORDAT", length = 19)
	public Date getZasordat() {
		return this.zasordat;
	}

	public void setZasordat(Date zasordat) {
		this.zasordat = zasordat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DAT", length = 19)
	public Date getDat() {
		return this.dat;
	}

	public void setDat(Date dat) {
		this.dat = dat;
	}

}
