package com.hk.deader.domains;

// Generated 20.12.2012 16:56:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Bonushistory generated by hbm2java
 */
@Entity
@Table(name = "BONUSHISTORY")
public class Bonushistory implements java.io.Serializable {

	private static final long serialVersionUID = 659837010393537387L;
	private BonushistoryId id;
	private int bonadd;
	private String operator;
	private String userid;

	public Bonushistory() {
	}

	public Bonushistory(BonushistoryId id, int bonadd, String operator,
			String userid) {
		this.id = id;
		this.bonadd = bonadd;
		this.operator = operator;
		this.userid = userid;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numkey", column = @Column(name = "NUMKEY", nullable = false, length = 6)),
			@AttributeOverride(name = "dat", column = @Column(name = "DAT", nullable = false, length = 19)) })
	public BonushistoryId getId() {
		return this.id;
	}

	public void setId(BonushistoryId id) {
		this.id = id;
	}

	@Column(name = "BONADD", nullable = false)
	public int getBonadd() {
		return this.bonadd;
	}

	public void setBonadd(int bonadd) {
		this.bonadd = bonadd;
	}

	@Column(name = "OPERATOR", nullable = false, length = 32)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "USERID", nullable = false, length = 16)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

}
