package com.hk.deader.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bonus generated by hbm2java
 */
@Entity
@Table(name = "BONUS")
public class Bonus implements java.io.Serializable {

	private static final long serialVersionUID = 7199010142605591858L;
	private String numkey;
	private Date dat;
	private int avtomat;
	private double bal;
	private double sumadd;
	private double sumsub;
	private double bon;
	private double bonadd;
	private char bonflag;
	private String operator;

	public Bonus() {
	}

	public Bonus(String numkey, Date dat, int avtomat, double bal,
			double sumadd, double sumsub, double bon, double bonadd,
			char bonflag, String operator) {
		this.numkey = numkey;
		this.dat = dat;
		this.avtomat = avtomat;
		this.bal = bal;
		this.sumadd = sumadd;
		this.sumsub = sumsub;
		this.bon = bon;
		this.bonadd = bonadd;
		this.bonflag = bonflag;
		this.operator = operator;
	}

	@Id
	@Column(name = "NUMKEY", unique = true, nullable = false, length = 6)
	public String getNumkey() {
		return this.numkey;
	}

	public void setNumkey(String numkey) {
		this.numkey = numkey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DAT", nullable = false, length = 19)
	public Date getDat() {
		return this.dat;
	}

	public void setDat(Date dat) {
		this.dat = dat;
	}

	@Column(name = "AVTOMAT", nullable = false)
	public int getAvtomat() {
		return this.avtomat;
	}

	public void setAvtomat(int avtomat) {
		this.avtomat = avtomat;
	}

	@Column(name = "BAL", nullable = false, precision = 15, scale = 0)
	public double getBal() {
		return this.bal;
	}

	public void setBal(double bal) {
		this.bal = bal;
	}

	@Column(name = "SUMADD", nullable = false, precision = 15, scale = 0)
	public double getSumadd() {
		return this.sumadd;
	}

	public void setSumadd(double sumadd) {
		this.sumadd = sumadd;
	}

	@Column(name = "SUMSUB", nullable = false, precision = 15, scale = 0)
	public double getSumsub() {
		return this.sumsub;
	}

	public void setSumsub(double sumsub) {
		this.sumsub = sumsub;
	}

	@Column(name = "BON", nullable = false, precision = 15, scale = 0)
	public double getBon() {
		return this.bon;
	}

	public void setBon(double bon) {
		this.bon = bon;
	}

	@Column(name = "BONADD", nullable = false, precision = 15, scale = 0)
	public double getBonadd() {
		return this.bonadd;
	}

	public void setBonadd(double bonadd) {
		this.bonadd = bonadd;
	}

	@Column(name = "BONFLAG", nullable = false, length = 1)
	public char getBonflag() {
		return this.bonflag;
	}

	public void setBonflag(char bonflag) {
		this.bonflag = bonflag;
	}

	@Column(name = "OPERATOR", nullable = false, length = 32)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

}
