package com.hk.deader.domains;

// Generated 20.12.2012 16:56:41 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BonushistoryId generated by hbm2java
 */
@Embeddable
public class BonushistoryId implements java.io.Serializable {

	private static final long serialVersionUID = 7277903477393232207L;
	private String numkey;
	private Date dat;

	public BonushistoryId() {
	}

	public BonushistoryId(String numkey, Date dat) {
		this.numkey = numkey;
		this.dat = dat;
	}

	@Column(name = "NUMKEY", nullable = false, length = 6)
	public String getNumkey() {
		return this.numkey;
	}

	public void setNumkey(String numkey) {
		this.numkey = numkey;
	}

	@Column(name = "DAT", nullable = false, length = 19)
	public Date getDat() {
		return this.dat;
	}

	public void setDat(Date dat) {
		this.dat = dat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BonushistoryId))
			return false;
		BonushistoryId castOther = (BonushistoryId) other;

		return ((this.getNumkey() == castOther.getNumkey()) || (this
				.getNumkey() != null && castOther.getNumkey() != null && this
				.getNumkey().equals(castOther.getNumkey())))
				&& ((this.getDat() == castOther.getDat()) || (this.getDat() != null
						&& castOther.getDat() != null && this.getDat().equals(
						castOther.getDat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNumkey() == null ? 0 : this.getNumkey().hashCode());
		result = 37 * result
				+ (getDat() == null ? 0 : this.getDat().hashCode());
		return result;
	}

}
