package com.hk.deader.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cash generated by hbm2java
 */
@Entity
@Table(name = "CASH")
public class Cash implements java.io.Serializable {

	private static final long serialVersionUID = -4864872428532938965L;
	private CashId id;
	private Integer litr;
	private Integer litrcash; // v kopeikah!!!!
	private Integer but;
	private Integer butcash;

	public Cash() {
	}

	public Cash(CashId id, int litr, int litrcash, int but, int butcash) {
		this.id = id;
		this.litr = litr;
		this.litrcash = litrcash;
		this.but = but;
		this.butcash = butcash;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dat", column = @Column(name = "DAT", nullable = false, length = 19)),
			@AttributeOverride(name = "avtomat", column = @Column(name = "AVTOMAT", nullable = false)) })
	public CashId getId() {
		return this.id;
	}

	public void setId(CashId id) {
		this.id = id;
	}

	@Column(name = "LITR", nullable = false)
	public int getLitr() {
		return this.litr;
	}

	public void setLitr(int litr) {
		this.litr = litr;
	}

	@Column(name = "LITRCASH", nullable = false)
	public int getLitrcash() {
		return this.litrcash;
	}

	public void setLitrcash(int litrcash) {
		this.litrcash = litrcash;
	}

	@Column(name = "BUT", nullable = false)
	public int getBut() {
		return this.but;
	}

	public void setBut(int but) {
		this.but = but;
	}

	@Column(name = "BUTCASH", nullable = false)
	public int getButcash() {
		return this.butcash;
	}

	public void setButcash(int butcash) {
		this.butcash = butcash;
	}

}
