package com.hk.deader.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Inkasshistory generated by hbm2java
 */
@Entity
@Table(name = "INKASSHISTORY")
public class Inkasshistory implements java.io.Serializable {

	private static final long serialVersionUID = -3312154897541817404L;
	private InkasshistoryId id;
	private Double sumadd;
	private Double sumtotal;
	private Double sumrez;
	private int avtomat;

	public Inkasshistory() {
	}

	public Inkasshistory(InkasshistoryId id, int avtomat) {
		this.id = id;
		this.avtomat = avtomat;
	}

	public Inkasshistory(InkasshistoryId id, Double sumadd, Double sumtotal,
			Double sumrez, int avtomat) {
		this.id = id;
		this.sumadd = sumadd;
		this.sumtotal = sumtotal;
		this.sumrez = sumrez;
		this.avtomat = avtomat;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dat", column = @Column(name = "DAT", nullable = false, length = 19)),
			@AttributeOverride(name = "datakey", column = @Column(name = "DATAKEY", nullable = false, length = 16)) })
	public InkasshistoryId getId() {
		return this.id;
	}

	public void setId(InkasshistoryId id) {
		this.id = id;
	}

	@Column(name = "SUMADD", precision = 15, scale = 0)
	public Double getSumadd() {
		return this.sumadd;
	}

	public void setSumadd(Double sumadd) {
		this.sumadd = sumadd;
	}

	@Column(name = "SUMTOTAL", precision = 15, scale = 0)
	public Double getSumtotal() {
		return this.sumtotal;
	}

	public void setSumtotal(Double sumtotal) {
		this.sumtotal = sumtotal;
	}

	@Column(name = "SUMREZ", precision = 15, scale = 0)
	public Double getSumrez() {
		return this.sumrez;
	}

	public void setSumrez(Double sumrez) {
		this.sumrez = sumrez;
	}

	@Column(name = "AVTOMAT", nullable = false)
	public int getAvtomat() {
		return this.avtomat;
	}

	public void setAvtomat(int avtomat) {
		this.avtomat = avtomat;
	}

}
