package com.hk.deader.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Key generated by hbm2java
 */
@Entity
@Table(name = "KEY")
public class Key implements java.io.Serializable {

	private static final long serialVersionUID = 8436085657359319490L;
	private String datakey;
	private Date dat;
	private String operator;
	private String numkey;
	private String FIO;
	private String ugroup;
	private double bal;
	private double bon;
	private double bonadd;

	public Key() {
	}

	public Key(String datakey, Date dat, String operator, String numkey, String FIO,
			double bal, double bon, double bonadd) {
		this.datakey = datakey;
		this.dat = dat;
		this.setFIO(FIO);
		this.operator = operator;
		this.numkey = numkey;
		this.bal = bal;
		this.bon = bon;
		this.bonadd = bonadd;
	}

	@Id
	@Column(name = "DATAKEY", unique = true, nullable = false, length = 16)
	public String getDatakey() {
		return this.datakey;
	}

	public void setDatakey(String datakey) {
		this.datakey = datakey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DAT", nullable = false, length = 19)
	public Date getDat() {
		return this.dat;
	}

	public void setDat(Date dat) {
		this.dat = dat;
	}

	@Column(name = "OPERATOR", nullable = false, length = 32)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "NUMKEY", nullable = false, length = 6)
	public String getNumkey() {
		return this.numkey;
	}

	public void setNumkey(String numkey) {
		this.numkey = numkey;
	}

	@Column(name = "BAL", nullable = false, precision = 15, scale = 0)
	public double getBal() {
		return this.bal;
	}

	public void setBal(double bal) {
		this.bal = bal;
	}

	@Column(name = "BON", nullable = false, precision = 15, scale = 0)
	public double getBon() {
		return this.bon;
	}

	public void setBon(double bon) {
		this.bon = bon;
	}

	@Column(name = "BONADD", nullable = false, precision = 15, scale = 0)
	public double getBonadd() {
		return this.bonadd;
	}

	public void setBonadd(double bonadd) {
		this.bonadd = bonadd;
	}
	
	@Column(name = "FIO", length = 100)
	public String getFIO() {
		return FIO;
	}

	public void setFIO(String fIO) {
		FIO = fIO;
	}

	@Column(name = "UGROUP", length = 2)
	public String getUgroup() {
		return ugroup;
	}

	public void setUgroup(String ugroup) {
		this.ugroup = ugroup;
	}

}
