package com.hk.deader.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Keyhistory generated by hbm2java
 */
@Entity
@Table(name = "KEYHISTORY")
public class Keyhistory implements java.io.Serializable {

	private static final long serialVersionUID = -6676602172937227330L;
	private KeyhistoryId id;
	private Double sumadd;
	private String terminal;
	private Double sumsub;
	private Double sumbut;
	private Integer avtomat;
	private Integer but;
	private Integer litr;

	public Keyhistory() {
	}

	public Keyhistory(KeyhistoryId id, int but, Integer litr) {
		this.id = id;
		this.but = but;
		this.litr = litr;
	}

	public Keyhistory(KeyhistoryId id, Double sumadd, String terminal,
			Double sumsub, Double sumbut, Integer avtomat, Integer but, Integer litr) {
		this.id = id;
		this.sumadd = sumadd;
		this.terminal = terminal;
		this.sumsub = sumsub;
		this.sumbut = sumbut;
		this.avtomat = avtomat;
		this.but = but;
		this.litr = litr;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dat", column = @Column(name = "DAT", nullable = false, length = 19)),
			@AttributeOverride(name = "numkey", column = @Column(name = "NUMKEY", nullable = false, length = 6)) })
	public KeyhistoryId getId() {
		return this.id;
	}

	public void setId(KeyhistoryId id) {
		this.id = id;
	}

	@Column(name = "SUMADD", precision = 15, scale = 0)
	public Double getSumadd() {
		return this.sumadd;
	}

	public void setSumadd(Double sumadd) {
		this.sumadd = sumadd;
	}

	@Column(name = "TERMINAL", length = 2)
	public String getTerminal() {
		return this.terminal;
	}

	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}

	@Column(name = "SUMSUB", precision = 15, scale = 0)
	public Double getSumsub() {
		return this.sumsub;
	}

	public void setSumsub(Double sumsub) {
		this.sumsub = sumsub;
	}

	@Column(name = "SUMBUT", precision = 15, scale = 0)
	public Double getSumbut() {
		return this.sumbut;
	}

	public void setSumbut(Double sumbut) {
		this.sumbut = sumbut;
	}

	@Column(name = "AVTOMAT")
	public Integer getAvtomat() {
		return this.avtomat;
	}

	public void setAvtomat(Integer avtomat) {
		this.avtomat = avtomat;
	}

	@Column(name = "BUT", nullable = false)
	public Integer getBut() {
		return this.but;
	}

	public void setBut(Integer but) {
		this.but = but;
	}

	@Column(name = "LITR", nullable = false)
	public Integer getLitr() {
		return this.litr;
	}

	public void setLitr(Integer litr) {
		this.litr = litr;
	}

}
