package com.hk.deader.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MoneyId generated by hbm2java
 */
@Embeddable
public class MoneyId implements java.io.Serializable {

	private static final long serialVersionUID = -8358630621848795604L;
	private Date dat;
	private int avtomat;

	public MoneyId() {
	}

	public MoneyId(Date dat, int avtomat) {
		this.dat = dat;
		this.avtomat = avtomat;
	}

	@Column(name = "DAT", nullable = false, length = 19)
	public Date getDat() {
		return this.dat;
	}

	public void setDat(Date dat) {
		this.dat = dat;
	}

	@Column(name = "AVTOMAT", nullable = false)
	public int getAvtomat() {
		return this.avtomat;
	}

	public void setAvtomat(int avtomat) {
		this.avtomat = avtomat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MoneyId))
			return false;
		MoneyId castOther = (MoneyId) other;

		return ((this.getDat() == castOther.getDat()) || (this.getDat() != null
				&& castOther.getDat() != null && this.getDat().equals(
				castOther.getDat())))
				&& (this.getAvtomat() == castOther.getAvtomat());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDat() == null ? 0 : this.getDat().hashCode());
		result = 37 * result + this.getAvtomat();
		return result;
	}

}
