package com.hk.deader.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Money generated by hbm2java
 */
@Entity
@Table(name = "MONEY")
public class Money implements java.io.Serializable {

	private static final long serialVersionUID = -5517481039579219364L;
	private MoneyId id;
	private int kop;
	private int spis;

	public Money() {
	}

	public Money(MoneyId id, int kop, int spis) {
		this.id = id;
		this.kop = kop;
		this.spis = spis;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dat", column = @Column(name = "DAT", nullable = false, length = 19)),
			@AttributeOverride(name = "avtomat", column = @Column(name = "AVTOMAT", nullable = false)) })
	public MoneyId getId() {
		return this.id;
	}

	public void setId(MoneyId id) {
		this.id = id;
	}

	@Column(name = "KOP", nullable = false)
	public int getKop() {
		return this.kop;
	}

	public void setKop(int kop) {
		this.kop = kop;
	}

	@Column(name = "SPIS", nullable = false)
	public int getSpis() {
		return this.spis;
	}

	public void setSpis(int spis) {
		this.spis = spis;
	}

}
