package com.hk.deader.domains;

// Generated 17.10.2012 10:26:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vodahistory generated by hbm2java
 */
@Entity
@Table(name = "VODAHISTORY")
public class Vodahistory implements java.io.Serializable {

	private static final long serialVersionUID = 6135029094939703425L;
	private VodahistoryId id;
	private Double litr;
	private Double sumadd;

	public Vodahistory() {
	}

	public Vodahistory(VodahistoryId id) {
		this.id = id;
	}

	public Vodahistory(VodahistoryId id, Double litr, Double sumadd) {
		this.id = id;
		this.litr = litr;
		this.sumadd = sumadd;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dat", column = @Column(name = "DAT", nullable = false, length = 19)),
			@AttributeOverride(name = "avtomat", column = @Column(name = "AVTOMAT", nullable = false)) })
	public VodahistoryId getId() {
		return this.id;
	}

	public void setId(VodahistoryId id) {
		this.id = id;
	}

	@Column(name = "LITR", precision = 15, scale = 0)
	public Double getLitr() {
		return this.litr;
	}

	public void setLitr(Double litr) {
		this.litr = litr;
	}

	@Column(name = "SUMADD", precision = 15, scale = 0)
	public Double getSumadd() {
		return this.sumadd;
	}

	public void setSumadd(Double sumadd) {
		this.sumadd = sumadd;
	}

}
